version: '3'
services:
  db:
    image: mysql:latest
    container_name: 'test'
    ports:
      - "13306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "TZ=Asia/Tokyo"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d
